import Navbar from './components/navbar'
import styles from './styles.module.css';
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'HAYATO FUJIWARA',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        {/* <Navbar /> */}
        {/* Landing Page */}
        <div className='w-full overflow-hidden'>
          <h1 className='absolute z-10 top-1/2 translate-y-1/2 translate-x-1/2 text-4xl'>HAYATO FUJIWARA</h1>
          <div className={styles.lpbg}></div>
        </div>
        {children}
        <footer></footer>
        </body>
    </html>
  )
}
